os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - composer update
  - composer install --no-interaction
  - cp .env.travis .env
  - composer require --dev squizlabs/php_codesniffer
  - phpenv rehash
  - composer dump-autoload
  - nvm install --lts
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs
  - npm run production
  - jshint resources/js/*